# This workflow is used to check backwards compatibility

name: Backwards

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup environment
      run: |
        python .ci_support/condamerge.py --base .ci_support/environment.yml --add .ci_support/environment-notebooks.yml > environment.yml
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: '3.10'
        miniforge-variant: Mambaforge
        channels: conda-forge
        channel-priority: strict
        activate-environment: my-env
        use-mamba: true
    - name: Set cache date
      run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
    - uses: actions/cache@v2
      with:
        path: /usr/share/miniconda3/envs/my-env
        key: linux-64-py-3-10-conda-${{ hashFiles('environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
      id: cache
    - name: Update environment
      run: mamba env update -n my-env -f environment.yml
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Setup
      shell: bash -l {0}
      run: |
        python .ci_support/pyironconfig.py
        conda env update --name test --file .ci_support/environment-notebooks.yml
    - name: Test
      shell: bash -l {0}
      run: ./.ci_support/test_backwards.sh
